{
 "title": "Volume Analysis",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "BTCUSDT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Quote Volume for BTCUSDT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT \n  start_time AS \"time\", \n  total_quote_volume \nFROM qvb_1m \nWHERE $__timeFilter(start_time) \nAND symbol = 'BTCUSDT' \nORDER BY start_time ASC;\n"
    }
   ]
  },
  {
   "title": "ETHUSDT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Total Quote Volume for ETHUSDT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT \n  start_time AS \"time\", \n  total_quote_volume \nFROM qvb_1m\nWHERE $__timeFilter(start_time) \nAND symbol = 'ETHUSDT' \nORDER BY start_time ASC;\n"
    }
   ]
  },
  { "title": "BNBUSDT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Quote Volume for BNBUSDT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT \n  start_time AS \"time\", \n  total_quote_volume \nFROM qvb_1m\nWHERE $__timeFilter(start_time) \nAND symbol = 'BNBUSDT' \nORDER BY start_time ASC;\n"
    }
   ]
  },
  {
   "title": "AI suggestion",
   "type": "table",
   "gridPos": { "h": 18, "w": 23, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT suggestion, symbol, analysis_time\nFROM qvb_1m_suggest\nORDER BY analysis_time DESC\nLIMIT 1;\n"
    }
   ]
  }
 ]
}