{
 "title": "Volume and MA",
 "description": "Volume by time off ETH",
 "time": { "from": "2025-10-30T02:19:30.000Z", "to": "2025-10-30T03:31:00.000Z" },
 "panels": [
  { "title": "ETH-USDT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ETHUSDT",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT symbol, alert_value, old_value, alert_type FROM crypto_alert\r\nWHERE symbol ='ETHUSDT'\r\nORDER BY alert_time DESC"
    }
   ]
  },
  {
   "title": "Alert History",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT alert_time,alert_type, alert_value, old_value as reference_value  \r\nFROM crypto_alert\r\nWHERE symbol ='ETHUSDT'\r\nORDER BY alert_time DESC"
    }
   ]
  },
  {
   "title": "ETHUSDT",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT window_start,total_volume FROM crypto_volume\r\nWHERE crypto_volume.symbol = 'ETHUSDT'"
    },
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT time_start, ma_value FROM crypto_ma \r\nwhere symbol = 'ETHUSDT'"
    }
   ]
  },
  {
   "title": "BNB-USDT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "BNBUSDT",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "crypto_db",
       "rawSql": "SELECT symbol, alert_value, old_value, alert_type FROM crypto_alert\r\nWHERE symbol ='BNBUSDT'\r\nORDER BY alert_time DESC"
      }
     ]
    },
    {
     "title": "Alert History",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 54 },
     "targets": [
      {
       "dataset": "crypto_db",
       "rawSql": "SELECT alert_time,alert_type, alert_value, old_value as reference_value  \r\nFROM crypto_alert\r\nWHERE symbol ='BNBUSDT'\r\nORDER BY alert_time DESC"
      }
     ]
    },
    {
     "title": "BNBUSDT",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "dataset": "crypto_db",
       "rawSql": "SELECT window_start,total_volume FROM crypto_volume\r\nWHERE crypto_volume.symbol = 'BNBUSDT'"
      },
      {
       "dataset": "crypto_db",
       "rawSql": "SELECT time_start, ma_value FROM crypto_ma \r\nwhere symbol = 'BNBUSDT'"
      }
     ]
    }
   ]
  },
  {
   "title": "BTC-USDT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "BTCUSDT",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "crypto_db",
       "rawSql": "SELECT symbol, alert_value, old_value, alert_type FROM crypto_alert\r\nWHERE symbol ='BTCUSDT'\r\nORDER BY alert_time DESC"
      }
     ]
    },
    {
     "title": "Alert History",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 81 },
     "targets": [
      {
       "dataset": "crypto_db",
       "rawSql": "SELECT alert_time,alert_type, alert_value, old_value as reference_value  \r\nFROM crypto_alert\r\nWHERE symbol ='BTCUSDT'\r\nORDER BY alert_time DESC"
      }
     ]
    },
    {
     "title": "BTCUSDT",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 90 },
     "targets": [
      {
       "dataset": "crypto_db",
       "rawSql": "SELECT window_start,total_volume FROM crypto_volume\r\nWHERE crypto_volume.symbol = 'BTCUSDT'"
      },
      {
       "dataset": "crypto_db",
       "rawSql": "SELECT time_start, ma_value FROM crypto_ma \r\nwhere symbol = 'BTCUSDT'"
      }
     ]
    }
   ]
  }
 ]
}