services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - real-time-net


  binance-stream:
    build:
      context: ./src/ingestion
      dockerfile: ingestion.Dockerfile
    container_name: binance-stream
    depends_on:
      - kafka
    volumes:
      - ./src/ingestion:/app
    command: 
      - ["sleep", "infinity"]
      # - ["python", "-u", "./src/makeStream.py"]
    networks:
      - real-time-net


  spark-master:
      image: bitnami/spark:3.5.3
      environment:
        - SPARK_MODE=master
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
        - SPARK_MASTER_WEBUI_PORT=8080
        - SPARK_DAEMON_MEMORY=1g
      ports:
        - "7077:7077"   # Spark master RPC
        - "8080:8080"   # Spark master UI
      volumes:
        - ./src:/opt/workspace
      networks: [real-time-net]
      workspace: /opt/workspace

  spark-worker:
    image: bitnami/spark:3.5.3
    depends_on: [spark-master]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4g
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_DAEMON_MEMORY=1g
    ports:
      - "8081:8081"   # Worker 1 UI
    volumes:
      - ./src:/opt/workspace
    networks: [real-time-net]

networks:
  real-time-net:
    driver: bridge