version: '3.9'

services:
  kafka:
    image: apache/kafka:4.0.1-rc2
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "19092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data  
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "18085:8080"  
    environment:
      KAFKA_CLUSTERS_0_NAME: kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092  
      KAFKA_CLUSTERS_0_ZOOKEEPER: ""              
    depends_on:
      - kafka

  binance-stream:
    build:
      context: ./ingestion
      dockerfile: ingestion.Dockerfile
    container_name: binance-stream
    volumes:
      - ./ingestion:/app
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      sh -c "python src/send_data.py & wait"



  spark-master:
    build:
      context: ./spark
      dockerfile: spark.Dockerfile
    user: root
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "17077:7077"
      - "18080:8080"
    environment:
      SPARK_MODE: master
    volumes:
      - ./spark-apps:/opt/workspace
    working_dir: /opt/workspace

  spark-worker:
    build:
      context: ./spark
      dockerfile: spark.Dockerfile
    user: root
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./spark-apps:/opt/workspace


  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: crypto_db
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:12.3.0-18701397209
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: your_grafana_password
    ports:
      - "13000:3000"
    depends_on:
      - postgres
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  pgdata:
  grafana-storage:
  kafka-data: