services:
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    networks:
      - real-time-net

  python:
    image: python:3.9-slim

  spark-master:
      image: bitnami/spark:3.5.3
      environment:
        - SPARK_MODE=master
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
        - SPARK_MASTER_WEBUI_PORT=8080
        - SPARK_DAEMON_MEMORY=1g
      ports:
        - "7077:7077"   # Spark master RPC
        - "8080:8080"   # Spark master UI
      volumes:
        - ./src:/opt/workspace
      networks: [real-time-net]

  spark-worker:
    image: bitnami/spark:3.5.3
    depends_on: [spark-master]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4g
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_DAEMON_MEMORY=1g
    ports:
      - "8081:8081"   # Worker 1 UI
    volumes:
      - ./src:/opt/workspace
    networks: [real-time-net]

volumes:
  src:
    driver: local
networks:
  real-time-net:
    driver: bridge