{
 "title": "Volume and MA",
 "description": "Volume by time off ETH",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "BTCUSDT",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT symbol, alert_value, old_value, alert_type FROM crypto_alert\r\nWHERE symbol ='BTCUSDT'\r\nORDER BY alert_time DESC"
    }
   ]
  },
  {
   "title": "BNBUSDT",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT symbol, alert_value, old_value, alert_type FROM crypto_alert\r\nWHERE symbol ='BNBUSDT'\r\nORDER BY alert_time DESC"
    }
   ]
  },
  {
   "title": "ETHUSDT",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT symbol, alert_value, old_value, alert_type FROM crypto_alert\r\nWHERE symbol ='ETHUSDT'\r\nORDER BY alert_time DESC"
    }
   ]
  },
  {
   "title": "ETHUSDT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT window_start,total_volume FROM crypto_volume\r\nWHERE crypto_volume.symbol = 'ETHUSDT'"
    },
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT time_start, ma_value FROM crypto_ma \r\nwhere symbol = 'ETHUSDT'"
    }
   ]
  },
  {
   "title": "BNBUSDT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT window_start,total_volume FROM crypto_volume\r\nWHERE crypto_volume.symbol = 'BNBUSDT'"
    },
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT time_start, ma_value FROM crypto_ma \r\nwhere symbol = 'BNBUSDT'"
    }
   ]
  },
  {
   "title": "BTCUSDT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT window_start,total_volume FROM crypto_volume\r\nWHERE crypto_volume.symbol = 'BTCUSDT'"
    },
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT time_start, ma_value FROM crypto_ma \r\nwhere symbol = 'BTCUSDT'"
    }
   ]
  }
 ]
}